### ISSUE TITLE
Table layout breaks when cell text contains ANSI color patterns

### ISSUE THREAD

**Issue by alexbool** [phsym/prettytable-rs#2]
When using `Table` with ordinary characters I get a nice and pretty table like this:
```
+------+-------+-------+--------+-------+-------+--------+-------+--------+--------+
|      | M1    | M2    | M4     | M5    | M10   | M15    | M20   | M30    | M60    |
+------+-------+-------+--------+-------+-------+--------+-------+--------+--------+
| VTBR | 7.55% | 0.21% | -4.37% | 1.56% | 8.49% | -1.78% | 4.95% | -5.95% | -3.80% |
+------+-------+-------+--------+-------+-------+--------+-------+--------+--------+
```

When I start to paint the text inside cells with `ansi_term` crate, I get this:
```
+-------------+--------------+--------------+---------------+--------------+--------------+---------------+--------------+---------------+---------------+
|             | M1  | M2  | M4   | M5  | M10 | M15  | M20 | M30  | M60  |
+-------------+--------------+--------------+---------------+--------------+--------------+---------------+--------------+---------------+---------------+
| VTBR | 7.55% | 0.21% | -4.37% | 1.56% | 8.49% | -1.78% | 4.95% | -5.95% | -3.80% |
+-------------+--------------+--------------+---------------+--------------+--------------+---------------+--------------+---------------+---------------+
```
Seems like ANSI chars are treated as 'normal' printable symbols which is obviously not true.

**Comment by phsym** [comment]
Indeed, ANSI escape sequences should not be treated as 'normal' printable chars.
The issue has 2 reason :
* **unicode_width** crate does not handle ansi escape sequences
* Rust Formatter does not handle them either when using alignment capability. For example in
```rust
write!(out, " {: ^1$} ", self.style.paint(c), col_width)
```

But I'm pretty sure I can work-around this.

Directly inserting string with escape sequences in a table may have many bad consequences (for exemple in multi-lines cells, or in tables printed into a cell). That's why I've been thinking about adding style management directly into the table API. I mean, adding methods to set cells / columns / rows style.

Also, I'm still not sure if I should use **ansi_term** crate, or the **term** crate which would also work on non-ansi terminals.

Any thought about that ?

**Comment by alexbool** [comment]
`term` crate:
* more downloads on `crates.io`
* works on Windows
* API based on `Terminal` trait (basically wrapper around `Write`), cannot print text into a `String`

`ansi_term` crate:
* doesn't work on Windows
* API based on `ANSIString` struct (wrapper around `Cow<'a, str>`), which is `Display`

So this will be a tough choce...

**Comment by phsym** [comment]
In your case, do you mind which crate is used ?

Concerning the `term` crate, since `Terminal` is a wrapper around `Write`, I think it would be quite easy to write a into a string with ANSI codes if needed.

I started some experimentations. Using `ansi_term` led me to big troubles because of those invisible chars. On the opposite, `term` crate only insert the chars when printing (or call Win API), so it's much more easier to integrate.

**Comment by alexbool** [comment]
Personally I will be happy with any working variant regardless of implementation details :)

**Comment by phsym** [comment]
Great !

**Comment by phsym** [comment]
It's still a work in progress for now, but you can already get and use the first draft from the **term_style** branch.
You can set your **Cargo.toml** to get it directly from github instead of crates.io.

I'll try to add an easy way to specify style in macros invocation. Once completed, I'll update online documentation, add some example code and publish version 0.4.0 on **crates.io**

The way to add style for now is to add attributes (provided by `term` crate) to a Cell

```rust
extern crate term;
use term::{Attr, color};

(...)

table.add_row(Row::new(vec![
    	Cell::new("foobar2")
                .with_style(Attr::ForegroundColor(color::GREEN))
                .with_style(Attr::Bold),
        Cell::new("bar2")
                .with_style(Attr::ForegroundColor(color::RED)),
        Cell::new("foo2")])
);
```

I'll work on an easier solution using macros.

**Comment by alexbool** [comment]
Tried it. It works!
![cns0r5j](https://cloud.githubusercontent.com/assets/1283792/11019524/ba8be932-860d-11e5-8111-123299201832.gif)

**Comment by phsym** [comment]
Now you can set style and alignment directly in macros :

Some examples :

In rows, for each cells :
```rust
row![FrByb:"ABC", d:"DEFG", d:"HIJKLMN"];
```
Or for the whole row :
```rust
row![FY : "styled", "bar", "foo"];
```
In tables, for each cells :
```rust
table!([FrBybl:"A", FrBybc:"B", FrBybr:"C"], [d:123, d:234, d:345, d:456]);
```
Or for each rows :
```rust
table!(Frb:["A", "B", "C"], d:[1, 2, 3, 4], d:[1, 2, 3]);
```
Or you can use the syntax directly on cells :
```rust
Cell::new("foo2").style_spec("FrByb")
```

Let me explain the cryptic syntax for the style specifier :
**FrBybl** means **F**oreground **r**ed **B**ackground **y**ellow **b**old **l**eft
Easy, right ?

List of supported specifiers :
* **F** : **F**oreground (must be followed by a color specifier)
* **B** : **B**ackground (must be followed by a color specifier)
* **b** : **b**old
* **i** : **i**talic
* **u** : **u**nderline
* **c** : Align **c**enter
* **l** : Align **l**eft
* **r** : Align **r**ight
* **d** : **d**efault style

List of color specifiers :
* **r** : Red
* **b** : Blue
* **g** : Green
* **y** : Yellow
* **c** : Cyan
* **m** : Magenta
* **w** : White
* **d** : Black

And capital letters are for **bright** colors. Eg :
* **R** : Bright Red
* **B** : Bright Blue
* ... and so on ...

**Comment by alexbool** [comment]
I'm not using macros, but thanks anyway!

**Comment by phsym** [comment]
Ok, I'm writing this here for reference

**Comment by phsym** [comment]
v0.4.0 is published on crates.io. You can now get the latest modifications from it
