### ISSUE TITLE
ANSI escape codes appearing in piped output

### ISSUE THREAD

**Issue by keeperofdakeys** [phsym/prettytable-rs#21]
I'm using this library for one of my programs, but I'm getting ANSI escape codes when piping the output (IE: The output isn't to a terminal). From a quick look at the code, there is a terminal detection feature. So I'm not sure why this is happening.

For reference, I'm on linux, using rxvt-unicode as my terminal And if it helps, here is where I'm calling your library - https://github.com/keeperofdakeys/Process-Query/blob/master/src/psq/main.rs#L21.

**Comment by phsym** [comment]
Hi again !

Humm, I now the term library detects if the current terminal supports unicode, but I'm not sure it's aware you are piping the output to another program. I'll investigate into this tomorrow.

**Comment by keeperofdakeys** [comment]
I've had a quick look at the term library you're using, and it looks like it just checks for the TERM environment variable, and has no 'isatty' checks on stdout. There is a bug along the same lines there already https://github.com/Stebalien/term/issues/54 too.

I'm not sure if windows would suffer from the same problem.

**Comment by phsym** [comment]
I can use [atty](https://crates.io/crates/atty/) crate to detect if the stdout is a tty or not (in the `printstd` method), and use term to colorize only if it is. I tried, and colors are not displayed when redirecting the output (in a file or piped to another program).

However, there is some cases where colorizing when output is redirected may be needed. Eg, when piping to `more` or `less -R`, but I don't know any way to detect we are doing this. So I could maybe add a boolean argument to `printstd` to force colorizing even if not atatched to a tty stdout.

What do you think about that ?

Windows would not suffer from this (at least in the standard msdos like sh*tty terminal) since colors are not rendered with ANSI characters, but with windows system calls instead.

**Comment by keeperofdakeys** [comment]
Thanks for that, this seems to fix the issue. Having a flag for printstd is probably the best you can do, I don't know of anyway around this - most unix commands have to do this as well though.

**Comment by phsym** [comment]
Great. Instead of adding an argument flag to `printstd()` and break compatibility, I created `print_tty(bool)` method. `printstd()` now simply calls `print_tty(false)` and does not enforce colorization.

**Comment by keeperofdakeys** [comment]
Just FYI, I added a comment to the upstream bug, since this seems like something that the term library should tell you https://github.com/Stebalien/term/issues/54#issuecomment-183995165.

**Comment by phsym** [comment]
:+1:

**Comment by phsym** [comment]
Fixed published on crates.io in `v0.6.1`
