### ISSUE TITLE
panicked at 'Cannot print table to standard output : operation not supported by the terminal'

### ISSUE THREAD

**Issue by fitzgen** [phsym/prettytable-rs#40]
Inside Emacs's `M-x shell`, the `cargo benchcmp` command will always panic because of `prettytable`:

```
$ cargo benchcmp ~/scratch/before ~/scratch/after
thread 'main' panicked at 'Cannot print table to standard output : operation not supported by the terminal', /Users/fitzgen/.cargo/registry/src/github.com-1ecc6299db9ec823/prettytable-rs-0.6.5/src/lib.rs:173
stack backtrace:
   1:        0x103c9bafa - std::sys::backtrace::tracing::imp::write::h46f28e67d38b4637
   2:        0x103c9dabf - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
   3:        0x103c9cf85 - std::panicking::default_hook::h96c288d728df3ebf
   4:        0x103c9d536 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   5:        0x103c9d3d4 - std::panicking::begin_panic::hfbeda5aad583dc32
   6:        0x103c9d2f2 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   7:        0x103c05962 - prettytable::TableSlice::print_tty::h7f3d5c1f5cfe8a0a
   8:        0x103bff5fd - cargo_benchcmp::Args::run::h5c6cc5028d1347fb
   9:        0x103bfa6e9 - cargo_benchcmp::main::hb31fd77d8a66a286
  10:        0x103c9e07a - __rust_maybe_catch_panic
  11:        0x103c9cac6 - std::rt::lang_start::haaae1186de9de8cb
```

Ideally, `prettytable` would check if pretty colors or whatever are supported (which `M-x shell` actually *will* support, so maybe just removing whatever check will work?) and not use them if they aren't, rather than panicking.

(Originally filed as https://github.com/BurntSushi/cargo-benchcmp/issues/15)

**Comment by phsym** [comment]
Hi,

Actually, the `prettytable` already perform some checks. As you can see in [lib.rs](https://github.com/phsym/prettytable-rs/blob/master/src/lib.rs#L167).
When calling `print_tty(bool)`, it checks the output is a tty, use the `term` crate if it is, and fallbacks to standard printing (with no colors) if not a tty.
If `true` is passed to `print_tty`, then it forces the use of the `term` crate.

In the case of `cargo-benchcmp`, `print_tty` is called with true, bypassing the check to force use of colors. The panic is caused by the `term` crate returning the error "**operation not supported by the terminal**"

However, prettytable is supposed to ignore unsupported operations, and continue by simply not applying them (as you can see in [cell.rs](https://github.com/phsym/prettytable-rs/blob/master/src/cell.rs#L187)). Only IO errors should cause a panic.

After a quick look, I guess the `NotSupported` error comes from the [reset call](https://github.com/phsym/prettytable-rs/blob/master/src/cell.rs#L192)
sent from by [term](https://github.com/Stebalien/term/blob/1581d6a725daeffbfbdf2b72bb7abafe1bfda9c2/src/terminfo/mod.rs#L115 )

I'll try to fix this ASAP. But I'm not an emacs user, I'll first need to check how to reproduce.

**Comment by fitzgen** [comment]
Thanks for the analysis!

Here are some steps to reproduce:

* Open emacs
* Type `M-x` (typically `ESC` and then `x`, or holding `ALT` and then pressing `x`) and type `shell` and then return
* This should open up a terminal inside of emacs
* Then execute `cargo benchcmp before after` for some `before` and `after` bench results (or do some other thing that invokes prettytable, I suppose?)

Let me know if those steps don't reproduce for you. Cheers!

**Comment by phsym** [comment]
I'm working on a fix. As a workaround you can change the `TERM` env variable in te emacs shell.
I tried 
* `export TERM=xterm-256color` or `TERM=xterm` which prints colors mixed with ANSI escape codes
* `export TERM=cygwin` which works nice with colors

BTW: The fix will only prevents the panic, but you won't get any color with the default `TERM=dumb`

**Comment by fitzgen** [comment]
Thanks! Let me know when a new version is published and I'll submit an upstream PR to point to the new version. Thanks again!

**Comment by phsym** [comment]
Done publishing in version `0.6.6`
